version: '3'

services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      EXPOSED_PORT: 3000
    ports:
      - 3000:3000
    networks:
      application:
        aliases:
          - frontend.local

  backend:
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    container_name: backend
    environment:
      EXPOSED_PORT: 5000
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DEEPL_API_KEY: ${DEEPL_API_KEY}
    ports:
      - 5001:5000
    networks:
      application:
        aliases:
          - backend.local

networks:
  application:
    driver: bridge