version: '3'

services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      EXPOSED_PORT: 3210
    ports:
      - 3210:3210
    volumes:
      - ./frontend/dist:/frontend/dist:rw
    networks:
      application:
        aliases:
          - frontend.local

  backend:
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    container_name: backend
    environment:
      EXPOSED_PORT: 5432
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DEEPL_API_KEY: ${DEEPL_API_KEY}
    ports:
      - 5432:5432
    networks:
      application:
        aliases:
          - backend.local

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - frontend

networks:
  application:
    driver: bridge